# Generated by Django 3.2.8 on 2021-11-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211112_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
