# Generated by Django 3.0 on 2021-11-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20211113_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={},
        ),
    ]
