# Generated by Django 3.0 on 2021-11-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20211114_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='people',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='preparation_time',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='item', to='customer.Category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='menu_images/'),
        ),
    ]
