# Generated by Django 3.2.8 on 2021-11-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_aboutus_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='slug',
        ),
    ]
